### ISSUE TITLE
Off-line data display

### ISSUE THREAD

**Issue by hua812586** [vilari-mickopf/mmwave-gesture-recognition#10]
Hello @vilari-mickopf.
I'm sorry to bother you again. I have a new problem, that is, how to display the data in the mmwave\data\ file as dynamically as in the plotter through offline mode.

Because I want to verify the correctness of the data I collected on the other radar boards in this way.

**Comment by vilari-mickopf** [comment]
This has been rewritten and it will come soon, but for now here is dirty fix. You can use load_sample func from #9 and in plotter's draw_last_sample substitute:
`last_sample = self.__get_previos_data(gesture)` with `last_sample = load_sample(gesture)`.

```python
plotter = Plotter(queue.Queue())
plotter.show()
plotter.draw_last_sample(<path>)
```

**Comment by vilari-mickopf** [comment]
Or even easier, you can just substitue at line [85](https://github.com/vilari-mickopf/mmwave-gesture-recognition/blob/a93f404c49c3797e441d456830e06f540abc4032/mmwave/utils/plotter.py#L85C2-L85C2):
```python
last_sample = Logger.get_last_sample(gesture)
if last_sample[-1] == '/':
    return None 
df = pd.read_csv(last_sample).reset_index().values
```

with 
```python
df = pd.read_csv(gesture).reset_index().values
```
and then again, instead of passing the gesture, you pass desired path to `plotter.draw_last_sample` method.

**Comment by hua812586** [comment]
Okay, I'll try both of those. Thank you very much for your clarification.

**Comment by hua812586** [comment]
Hello @vilari-mickopf. I'm bothering you again.
I modify the characteristics of the training (mainly in get_all_data-->get_data) and the monitored data (mainly in do_predict-->__predict_thread) on the basis of your code, but when plotting, obj is not displayed properly, what is this because? (I commented out the x, y handling in the plot_detected_objs and __get_previos_data functions).
![image](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/7288e2fc-c9a6-427a-b5e5-401565a85a7c)
![image](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/d18f7347-da5a-455c-b79b-c7177f613607)
![image](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/3b541f6e-3afd-403f-8d71-ac53610bfafd)

**Comment by vilari-mickopf** [comment]
Sorry for delay, repo is now updated and supports offline plotting. Have a look at __main__ in mmwave_gesture/utils/plotter.py for an example. Data and models are now hosted on dropbox, so follow readme on how to get them (additional data is also recorded).
