### ISSUE TITLE
Questions about the data

### ISSUE THREAD

**Issue by Song626** [vilari-mickopf/mmwave-gesture-recognition#4]
Hello, I am a college student from China. Thank you very much that your code is very clear and helped me a lot. However, I found that there is no data in the data folder. Could you please share all the .csv files in the data folder to me, thank you very very much, and my email is 18145643207@163.com or 1171910321@stu.hit.edu.cn.

**Comment by vilari-mickopf** [comment]
Duplicate od #2. just download it from gitlab for now.
