### ISSUE TITLE
error: unknown profile

### ISSUE THREAD

**Issue by Awesome-Paella** [vilari-mickopf/mmwave-gesture-recognition#6]
![image](https://user-images.githubusercontent.com/88318580/156124448-950ec8f6-6a62-48df-9f43-bf2becac1fa2.png)
![image](https://user-images.githubusercontent.com/88318580/156124622-c668a619-1026-49e6-9dcf-02b80808d2f9.png)
The configuration file has been imported into the project file

**Comment by Awesome-Paella** [comment]
Mmwave gesture recognition is very helpful to me. The data training can be completed normally, but there is a problem during the test. The display port and can be connected normally, but the configuration file cannot be sent to the mmwave device. I use iwr1642 and sdk354. I don't know whether it is the cause of the error.

**Comment by vilari-mickopf** [comment]
I have no idea why is this happening for you. Some debug info would be helpful. For example in `console.py` file, on the line 462, right after `cfg = os.path.join(self.config_dir, args + '.cfg')`, can you add:
```python
print(f'{cfg=}')
print(f'{self.config_dir=}')
print(f'{self.default_config=}')
```
And post the results here

**Comment by vilari-mickopf** [comment]
It could be your workig dir actually. Try setting the working dir to the same dir that contains `console.py` file.

**Comment by Awesome-Paella** [comment]
> It could be your workig dir actually. Try setting the working dir to the same dir that contains `console.py` file.

Thanks for the guide, can you tell me how to do it in detail, I'm new to this

**Comment by vilari-mickopf** [comment]
That is depended on your IDE, I have no idea what are you using (it looks like you are using some IDE)

**Comment by Awesome-Paella** [comment]
The problem of unknown profile has been solved. Some changes have been made to the address format, and it works. in console.py file, on the line 59.
![image](https://user-images.githubusercontent.com/88318580/156482809-75334127-f0df-4fce-827a-a7a12327fd34.png)
