### ISSUE TITLE
Failed sending configuration

### ISSUE THREAD

**Issue by Awesome-Paella** [vilari-mickopf/mmwave-gesture-recognition#7]
The previous problem has been well solved with your help. Thank you very much. Now there are two new problems. The configuration file cannot be sent to the board. I use iwr1642 and mmwave_ sdk_ 03_ 05_ 00_ 04, which is slightly different from what you use, so do I need to change the configuration file.

In addition, during flash operation, the console only displays' Ping mmwave ', and the version information should be displayed according to the code.

Such as' get version...

              Done

              Version:

              Done’

Thanks again!
hfutball

![image](https://user-images.githubusercontent.com/88318580/156482879-0d4a5695-d9b0-4a19-9c45-87ca39040b85.png)
![image](https://user-images.githubusercontent.com/88318580/156485806-b81adac7-3b0e-4d29-81e7-1c05a45836fe.png)

**Comment by vilari-mickopf** [comment]
Are SOP0 and SOP2 closed?

**Comment by hfutball** [comment]
> Are SOP0 and SOP2 closed?

I tried another board iwr1843, and the flush was normal, but I still couldn't send the configuration successfully

**Comment by Awesome-Paella** [comment]
> Are SOP0 and SOP2 closed?

I confirmed that sop0 and sop2 are closed. I tried another board iwr1843. The flash writing is normal. There may be some problems with the board used before, but the configuration cannot be sent successfully.

**Comment by vilari-mickopf** [comment]
Have you removed jumper from SOP0 after flashing, and restarted the power?

**Comment by Awesome-Paella** [comment]
I have solved this problem and completed the reproduction with your help , thank you for sharing such a perfect source code.

**Comment by hua812586** [comment]
Hello vilari-mickopf and hfutball.
When I see your problem, I find that the problem is the same as mine.

I'm also using 1642, but when I turn off SOP0 and 2 in Ubuntu, I can write.bin files to flash and execute start normally. However, flash cannot be executed in Windows.
![image](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/87815789-991f-4ae4-b826-2d167050e9ea)


After I wrote the.bin file to flash in ubuntu system, I directly executed the start command in Windows system and found that sending the configuration file failed.
![image](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/adb92cee-9cac-4c54-ac79-3a5b3479249e)

I am very sorry to bother you and look forward to your reply.

**Comment by vilari-mickopf** [comment]
Have you removed SOP0 after flashing?

**Comment by hua812586** [comment]
It's been removed
![3837fa7ff5d8c5b2d2216dd6f49a083](https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/cee72c42-6bb1-40d7-8fa4-d06578653492)

**Comment by vilari-mickopf** [comment]
I have no win on my pc, so this is only tested on linux. I remember testing it once on windows few years ago, and it worked, but i do remember that data and cli ports have been in reverse order, so i've added this to console's mmwave_init method:

```python
if platform.system() == 'Windows':
    ports.sort(reverse=True)
```

Maybe there is no consistency with the order of detected ports in win, so you can try and comment that. If that's the case, then you will have to connect your board manually every time (there is connect option).

Also, i will push a lot of changes soon (probably beginning of august) so there might be some fixes for your issues.

**Comment by vilari-mickopf** [comment]
Also, just to be sure, you have reseted the board after removing sop0?

**Comment by hua812586** [comment]
After I removed SOP0, I reset both the data cable and the power cable.

I'll try it now, manually connecting the port.

**Comment by hua812586** [comment]
I changed True to False, can do flash, and can do start and send configuration files

if platform.system() == 'Windows':
    ports.sort(reverse=False)

<img width="776" alt="5992f1b782344ce9f97585453debae1" src="https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/098c3caf-2d7d-4e4a-b489-158362d26c88">
<img width="347" alt="c4152627bd6505cbb65f862683348bb" src="https://github.com/vilari-mickopf/mmwave-gesture-recognition/assets/107682608/923c3967-eadc-46fe-806b-8f38458037b8">

Thank you very, very much for your answer.

**Comment by vilari-mickopf** [comment]
Yup, order of detected ports in windows is unreliable then. This means flashing will probably work as well on win with this change. 
There is not much that can be done by me in terms of making connection automatically. For cases like this i have implemented `connect` option in console which will let you manually select port/rate for cli/data. I will add some small q/a section, explain this issue and how it can be solved.

**Comment by vilari-mickopf** [comment]
Actually, in new version of the code i am checking the baudrate of the connection, and if detected baudrate is different than selected one, i warn the user about it. However, this auto rate detection can only be done for open ports, and before sending `sensorStart` command to the board, data port is closed. But still, if ports are reversed, it should be detected that selected baudrate for cli is not good, and that can indicate this issue, stop autoconnection, and force the user to connect manually.

**Comment by hua812586** [comment]
Yes, there is a lot of uncertainty about automatic connection. Different devices have different problems. Manual connections avoid this problem to some extent.
